### ISSUE TITLE
Can not detect city by IP

### ISSUE THREAD

**Issue by uran1980** [lysenkobv/maxmind-geolite2-database#3]
I am test ip = '78.36.201.103'

Db v1.0.7 detect city as `Kaliningrad`
Db v1.0.8 can not detect city

**Comment by lysenkobv** [comment]
Hi @uran1980.

Databases were taken from official MaxMind website.
I can do nothing to handle specified IP.
There is an option to downgrade to `1.0.7` in your project if it works for you.

Cheers,
Bohdan

**Comment by lysenkobv** [comment]
Probably `GeoLite2` is not supposed to be precise as paid `GeoIP2` version.
